language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0

env:
 matrix:
  - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE


before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
#  - moodle-plugin-ci codechecker
# css lint is disabled as it doesn't want to ignore the moodle pix format for div background images
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
#  - moodle-plugin-ci validate
#  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat

